### ISSUE TITLE
Enhancement: VM Instance Management - Missing Instance Query and Direct VM Control

### ISSUE THREAD

**Issue by dsmello** [Ollem-io/Ansible-Module-HyperStack-Cloud#3]
## Issue Summary

The current `dsmello.cloud.cloud_manager` module provides environment-level VM management but lacks individual instance control capabilities needed for dynamic infrastructure automation.

## Current Behavior

The module successfully manages VMs within environments using this structure:
```yaml
- name: Manage VMs in environment
  dsmello.cloud.cloud_manager:
    name: "my-environment"
    state: present
    vms:
      - name: "vm-instance"
        size: large
        image: ubuntu-22.04
        state: running
```

However, it doesn't provide:
1. **Instance Discovery**: No way to query existing instances by IP/name
2. **Response Data**: No VM details returned (IPs, status, etc.)
3. **Direct Instance Control**: Cannot start/stop specific hibernated instances by name

## Expected Behavior

For dynamic infrastructure automation, we need:

### 1. Instance Query Capability
```yaml
- name: Get instance information
  dsmello.cloud.instance_info:
    name: "specific-instance-name"
  register: instance_details

# Should return: state, public_ip, private_ip, size, etc.
```

### 2. Response Data in VM Operations
```yaml
- name: Create/update VMs
  dsmello.cloud.cloud_manager:
    name: "environment"
    vms: [...]
  register: result

# result should include VM details like IPs, current states
```

### 3. Direct Instance Management
```yaml
- name: Start hibernated instance
  dsmello.cloud.instance:
    name: "hibernated-instance"
    state: running
```

## Use Case

**Dynamic Instance Revival**: In automated deployments, we need to:
1. Check if specific instances are hibernated by IP/name
2. Start hibernated instances before deployment
3. Get instance details for connection validation

Currently impossible without external API calls.

## Environment Details

- **Ansible**: 11.7.0
- **Python**: 3.11+
- **Collection**: dsmello.cloud v0.2.0
- **Use Case**: Multi-provider infrastructure automation

## Tested Scenarios

✅ **Working**: Environment management, VM creation/updates
❌ **Missing**: Instance discovery, hibernated instance revival, IP-based lookups

## Suggested Implementation

Consider adding:
1. `dsmello.cloud.instance_info` - Query specific instances
2. `dsmello.cloud.instance` - Direct instance state management  
3. Enhanced `cloud_manager` responses with VM details

This would enable full HyperStack automation workflows without external API dependencies.

## Priority

**Medium-High**: Blocks dynamic infrastructure automation use cases
